# This is a basic workflow to help you get started with Actions

name: Build Test

# Controls when the workflow will run
on:
  push:
    branches: [ production, staging, development ]
  pull_request:
    branches: [ production, staging, development ]
defaults:
  run:
    working-directory: ./
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        env: 
          CI : ""
        run: |
          npm ci
          npm run build
          npm test  
